DROP TABLE IF EXISTS PRODUIT;
CREATE TABLE PRODUIT
(
    ID_PRODUIT INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM_PRODUIT TEXT NOT NULL,
    PRIX_VENTE REAL NOT NULL,
    PRIX_ACHAT REAL NOT NULL,
    CHEMIN_ICONE TEXT NOT NULL,
    CATEGORIE TEXT CHECK (CATEGORIE IN ('BOISSON', 'CONFISERIE', 'SPECIAL'))
);

DROP TABLE IF EXISTS VENTE;
CREATE TABLE VENTE
(
    ID_VENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PRODUIT INTEGER CHECK ((ID_PRODUIT IS NULL AND ID_FORMULE IS NOT NULL) OR (ID_FORMULE IS NULL AND ID_PRODUIT IS NOT NULL)),
    ID_FORMULE INTEGER NULL,
    FOREIGN KEY(ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT),
    FOREIGN KEY(ID_FORMULE) REFERENCES FORMULE(ID_FORMULE)

);

	

DROP TABLE IF EXISTS "ELEVE";
CREATE TABLE ELEVE      
(
    ID_ELEVE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM TEXT NOT NULL,
    PRENOM TEXT NOT NULL
);                                              
                                           
DROP TABLE IF EXISTS "DETTE";
CREATE TABLE DETTE 
(
    ID_DETTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ELEVE_DETTE INTEGER NOT NULL,
    ID_VENTE INTEGER NOT NULL,
    CREANCE REAL NOT NULL,
    FOREIGN KEY(ID_ELEVE_DETTE) REFERENCES ELEVE(ID_ELEVE),
    FOREIGN KEY(ID_VENTE) REFERENCES VENTE(ID_VENTE)
);
     
                                           
DROP TABLE IF EXISTS "ADMIN";
CREATE TABLE ADMIN
(
    ID_ADMIN INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN TEXT NOT NULL,
    MDP TEXT NOT NULL
);

DROP TABLE IF EXISTS FORMULE;
CREATE TABLE FORMULE
(
    ID_FORMULE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_BOISSON INTEGER NOT NULL,
    ID_CONFISERIE INTEGER NOT NULL,
    FOREIGN KEY(ID_BOISSON) REFERENCES PRODUIT(ID_PRODUIT),
    FOREIGN KEY(ID_CONFISERIE) REFERENCES PRODUIT(ID_PRODUIT)
);

INSERT INTO ADMIN VALUES (1,"admin", "admin");

DROP TABLE IF EXISTS STOCK;
CREATE TABLE STOCK
(
ID_STOCK INTEGER PRIMARY KEY AUTOINCREMENT,
ID_PRODUIT INTEGER NOT NULL,
STOCK INTEGER NOT NULL,
FOREIGN KEY(ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
);
