DROP TABLE IF EXISTS PRODUIT;
CREATE TABLE PRODUIT
(
    ID_PRODUIT INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM_PRODUIT TEXT NOT NULL,
    PRIX_VENTE REAL NOT NULL,
    PRIX_ACHAT REAL NOT NULL,
    CATEGORIE TEXT CHECK (CATEGORIE IN ('BOISSON', 'CONFISERIE', 'SPECIAL'))
);

DROP TABLE IF EXISTS VENTE;
CREATE TABLE VENTE
(
    ID_VENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PRODUIT INTEGER CHECK ((ID_PRODUIT IS NULL AND ID_FORMULE IS NOT NULL) OR (ID_FORMULE IS NULL AND ID_PRODUIT IS NOT NULL)),
    ID_FORMULE INTEGER NULL
);

	

DROP TABLE IF EXISTS "ELEVE";
CREATE TABLE ELEVE      
(
    ID_ELEVE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM TEXT NOT NULL,
    PRENOM TEXT NOT NULL
);                                              
                                           
DROP TABLE IF EXISTS "DETTE";
CREATE TABLE DETTE 
(
    ID_DETTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ELEVE_DETTE TEXT NOT NULL,
    ID_VENTE INTEGER NOT NULL,
    CREANCE REAL NOT NULL
);
     
                                           
DROP TABLE IF EXISTS "ADMIN";
CREATE TABLE ADMIN
(
    ID_ADMIN INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN TEXT NOT NULL,
    MDP TEXT NOT NULL
);

