
DROP TABLE IF EXISTS PRODUIT;
CREATE TABLE PRODUIT
(
    ID_PRODUIT INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM_PRODUIT TEXT NOT NULL,
    PRIX_VENTE REAL NOT NULL,
    PRIX_ACHAT REAL NOT NULL,
    CHEMIN_ICONE TEXT NULL,
    CATEGORIE TEXT CHECK (CATEGORIE IN ('BOISSON', 'CONFISERIE', 'SPECIAL')),
    STOCK INTEGER NOT NULL
);

DROP TABLE IF EXISTS VENTE;
CREATE TABLE VENTE
(
    ID_VENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    DATE_VENTE TEXT NOT NULL,
    MONTANT REAL NOT NULL

);

	

DROP TABLE IF EXISTS "ELEVE";
CREATE TABLE ELEVE      
(
    ID_ELEVE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM TEXT NOT NULL,
    PRENOM TEXT NOT NULL
);                                              
                                           
DROP TABLE IF EXISTS "DETTE";
CREATE TABLE DETTE 
(
    ID_DETTE INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ELEVE_DETTE INTEGER NOT NULL,
    ID_VENTE INTEGER NOT NULL,
    CREANCE REAL NOT NULL,
    FOREIGN KEY(ID_ELEVE_DETTE) REFERENCES ELEVE(ID_ELEVE),
    FOREIGN KEY(ID_VENTE) REFERENCES VENTE(ID_VENTE)
);
     
                                           
DROP TABLE IF EXISTS "ADMIN";
CREATE TABLE ADMIN
(
    ID_ADMIN INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN TEXT NOT NULL,
    MDP TEXT NOT NULL
);



DROP TABLE IF EXISTS DETAIL_VENTE;
CREATE TABLE DETAIL_VENTE
(
ID_DETAIL_VENTE INTEGER PRIMARY KEY AUTOINCREMENT,
ID_VENTE INTEGER NOT NULL,
ID_PRODUIT INTEGER NOT NULL,
FOREIGN KEY(ID_VENTE) REFERENCES VENTE(ID_VENTE),
FOREIGN KEY(ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
);
